image: python:2.7-alpine

before_script:
  - apk add --no-cache --virtual .fetch-deps git perl
  - git clone --recursive --depth 1 https://github.com/getpelican/pelican-plugins.git
  - git clone https://gitlab.com/axil/pelican-uberspot.git

stages:
  - install
  - build

install:
  stage: install
  script: pip install -r requirements.txt

build:
  stage: build
  script: pelican -s settings_prod.py
  artifacts:
    paths:
    - public
